// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Polarion Client Contributors

// Package codegen provides code generation functionality for creating type-safe
// Go structs from Polarion work item types and their custom fields.
//
// The codegen package leverages the Polarion metadata discovery APIs to automatically
// generate Go code that provides type-safe access to custom fields in work items.
//
// # Overview
//
// The package consists of several components:
//
//   - Generator: Orchestrates the code generation process
//   - Discoverer: Discovers custom fields from Polarion metadata
//   - WorkItemTypeTemplate: Generates Go source code from field definitions
//   - Parser: Parses existing generated files for refresh mode
//
// # Basic Usage
//
// Create a generator and run code generation:
//
//	client, _ := polarion.New("https://polarion.example.com/rest/v1", "token")
//	config := &codegen.Config{
//	    OutputDir: "./generated",
//	    Package:   "generated",
//	    TypeID:    "requirement", // or empty for all types
//	    Refresh:   false,
//	}
//	gen := codegen.NewGenerator(client, "myproject", config)
//	if err := gen.Generate(ctx); err != nil {
//	    log.Fatal(err)
//	}
//
// # Generated Code Structure
//
// The generator creates Go structs with:
//
//   - Type-safe fields for each custom field
//   - LoadFromWorkItem method to populate from a WorkItem
//   - SaveToWorkItem method to save back to a WorkItem
//   - Getter and setter methods for each custom field
//   - Generation markers to separate generated and custom code
//
// # Field Type Mapping
//
// Polarion field kinds are mapped to Go types:
//
//   - string → *string
//   - text, text/html → *polarion.TextContent
//   - integer → *int
//   - float → *float64
//   - boolean → *bool
//   - date → *polarion.DateOnly
//   - time → *polarion.TimeOnly
//   - date-time → *polarion.DateTime
//   - duration → *polarion.Duration
//   - enumeration → *string (with enum name in comments)
//   - relationship → *string (relationship ID)
//
// All fields use pointer types to distinguish between "not set" and "zero value".
//
// # Refresh Mode
//
// The generator supports refreshing existing files while preserving custom code:
//
//	config := &codegen.Config{
//	    OutputDir: "./generated",
//	    Package:   "generated",
//	    Refresh:   true, // Enable refresh mode
//	}
//
// In refresh mode, the generator:
//
//  1. Parses existing files to find generation markers
//  2. Extracts custom code sections (outside markers)
//  3. Generates new code from current Polarion metadata
//  4. Merges code by replacing marker sections while preserving custom sections
//  5. Reports changes to the user
//
// # Generation Markers
//
// The generator uses markers to separate generated and custom code:
//
//   - GENERATED_FIELDS_START / GENERATED_FIELDS_END: Struct fields
//   - GENERATED_METHODS_START / GENERATED_METHODS_END: Generated methods
//
// Code between these markers will be overwritten during refresh.
// Custom code should be added outside these markers.
//
// # Example Generated Code
//
//	// Code generated by polarion-codegen. DO NOT EDIT manually between generation markers.
//	package generated
//
//	import (
//	    "fmt"
//	    polarion "github.com/almnorth/go-polarion"
//	)
//
//	// Requirement represents a custom requirement work item with type-safe field access.
//	type Requirement struct {
//	    base *polarion.WorkItem
//
//	    // GENERATED_FIELDS_START - Do not edit between markers
//	    // BusinessValue: Business Value
//	    BusinessValue *string
//	    // GENERATED_FIELDS_END
//
//	    // Add your custom fields here (they will be preserved during refresh)
//	}
//
//	// NewRequirement creates a new Requirement with initialized base WorkItem.
//	func NewRequirement(title string) *Requirement {
//	    return &Requirement{
//	        base: &polarion.WorkItem{
//	            Type: "workitems",
//	            Attributes: &polarion.WorkItemAttributes{
//	                Title:        title,
//	                CustomFields: make(map[string]interface{}),
//	            },
//	        },
//	    }
//	}
//
//	// GENERATED_METHODS_START - Do not edit between markers
//	// LoadFromWorkItem populates the Requirement from a work item.
//	func (w *Requirement) LoadFromWorkItem(wi *polarion.WorkItem) error {
//	    // ... generated code ...
//	}
//	// GENERATED_METHODS_END
//
// # Requirements
//
// The codegen package requires:
//
//   - Polarion 2512 or later (for Fields Metadata API)
//   - Valid Polarion authentication token
//   - Read access to the target project
//
// # See Also
//
//   - CLI tool: cmd/polarion-codegen
//   - Examples: examples/custom_workitems
//   - Documentation: docs/CUSTOM-WORKITEMS.md
package codegen
