// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Polarion Client Contributors

package codegen

import (
	"fmt"
	"strings"
	"time"

	polarion "github.com/almnorth/go-polarion"
)

// WorkItemTypeTemplate generates Go code for a work item type
type WorkItemTypeTemplate struct {
	packageName string
	projectID   string
	typeID      string
	typeName    string
	fields      []FieldInfo
}

// NewTemplate creates a new code template
func NewTemplate(packageName, projectID, typeID string, fields []FieldInfo) *WorkItemTypeTemplate {
	return &WorkItemTypeTemplate{
		packageName: packageName,
		projectID:   projectID,
		typeID:      typeID,
		typeName:    toTypeName(typeID),
		fields:      fields,
	}
}

// Generate generates the complete Go source code
func (t *WorkItemTypeTemplate) Generate() (string, error) {
	var sb strings.Builder

	// File header
	t.writeHeader(&sb)

	// Package declaration
	sb.WriteString(fmt.Sprintf("package %s\n\n", t.packageName))

	// Imports
	t.writeImports(&sb)

	// Struct definition
	t.writeStruct(&sb)

	// Constructor
	t.writeConstructor(&sb)

	// GENERATED_METHODS_START marker
	sb.WriteString("// GENERATED_METHODS_START - Do not edit between markers\n\n")

	// LoadFromWorkItem method
	t.writeLoadMethod(&sb)

	// SaveToWorkItem method
	t.writeSaveMethod(&sb)

	// Getter and setter methods for each field
	for _, field := range t.fields {
		t.writeGetterSetter(&sb, field)
	}

	// GENERATED_METHODS_END marker
	sb.WriteString("// GENERATED_METHODS_END\n\n")

	// GetBase method
	t.writeGetBaseMethod(&sb)

	// GetID method
	t.writeGetIDMethod(&sb)

	// GetTitle method
	t.writeGetTitleMethod(&sb)

	return sb.String(), nil
}

// writeHeader writes the file header comment
func (t *WorkItemTypeTemplate) writeHeader(sb *strings.Builder) {
	sb.WriteString("// Code generated by polarion-codegen. DO NOT EDIT manually between generation markers.\n")
	sb.WriteString(fmt.Sprintf("// Source: Polarion project %q, work item type %q\n", t.projectID, t.typeID))
	sb.WriteString(fmt.Sprintf("// Generated: %s\n\n", time.Now().UTC().Format(time.RFC3339)))
}

// writeImports writes the import statements
func (t *WorkItemTypeTemplate) writeImports(sb *strings.Builder) {
	sb.WriteString("import (\n")
	sb.WriteString("\t\"fmt\"\n\n")
	sb.WriteString("\tpolarion \"github.com/almnorth/go-polarion\"\n")
	sb.WriteString(")\n\n")
}

// writeStruct writes the struct definition
func (t *WorkItemTypeTemplate) writeStruct(sb *strings.Builder) {
	sb.WriteString(fmt.Sprintf("// %s represents a custom %s work item with type-safe field access.\n", t.typeName, t.typeID))
	sb.WriteString(fmt.Sprintf("type %s struct {\n", t.typeName))
	sb.WriteString("\tbase *polarion.WorkItem\n\n")

	if len(t.fields) > 0 {
		sb.WriteString("\t// GENERATED_FIELDS_START - Do not edit between markers\n")
		for _, field := range t.fields {
			if field.Description != "" {
				sb.WriteString(fmt.Sprintf("\t// %s: %s\n", field.GoName, field.Description))
			}
			if field.Kind == polarion.FieldKindEnumeration && field.EnumName != "" {
				sb.WriteString(fmt.Sprintf("\t// Enumeration: %s\n", field.EnumName))
			}
			sb.WriteString(fmt.Sprintf("\t%s %s\n\n", field.GoName, field.GoType))
		}
		sb.WriteString("\t// GENERATED_FIELDS_END\n\n")
		sb.WriteString("\t// Add your custom fields here (they will be preserved during refresh)\n")
	}

	sb.WriteString("}\n\n")
}

// writeConstructor writes the constructor function
func (t *WorkItemTypeTemplate) writeConstructor(sb *strings.Builder) {
	sb.WriteString(fmt.Sprintf("// New%s creates a new %s with initialized base WorkItem.\n", t.typeName, t.typeName))
	sb.WriteString(fmt.Sprintf("func New%s(title string) *%s {\n", t.typeName, t.typeName))
	sb.WriteString(fmt.Sprintf("\treturn &%s{\n", t.typeName))
	sb.WriteString("\t\tbase: &polarion.WorkItem{\n")
	sb.WriteString("\t\t\tType: \"workitems\",\n")
	sb.WriteString("\t\t\tAttributes: &polarion.WorkItemAttributes{\n")
	sb.WriteString("\t\t\t\tTitle:        title,\n")
	sb.WriteString("\t\t\t\tCustomFields: make(map[string]interface{}),\n")
	sb.WriteString("\t\t\t},\n")
	sb.WriteString("\t\t},\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")
}

// writeLoadMethod writes the LoadFromWorkItem method
func (t *WorkItemTypeTemplate) writeLoadMethod(sb *strings.Builder) {
	sb.WriteString(fmt.Sprintf("// LoadFromWorkItem populates the %s from a work item.\n", t.typeName))
	sb.WriteString(fmt.Sprintf("func (w *%s) LoadFromWorkItem(wi *polarion.WorkItem) error {\n", t.typeName))
	sb.WriteString("\tw.base = wi\n\n")
	sb.WriteString("\tif wi.Attributes == nil {\n")
	sb.WriteString("\t\treturn fmt.Errorf(\"work item attributes are nil\")\n")
	sb.WriteString("\t}\n\n")

	if len(t.fields) > 0 {
		sb.WriteString("\tcf := polarion.CustomFields(wi.Attributes.CustomFields)\n\n")

		for _, field := range t.fields {
			t.writeLoadField(sb, field)
		}
	}

	sb.WriteString("\treturn nil\n")
	sb.WriteString("}\n\n")
}

// writeLoadField writes the code to load a single field
func (t *WorkItemTypeTemplate) writeLoadField(sb *strings.Builder, field FieldInfo) {
	switch field.Kind {
	case polarion.FieldKindString, polarion.FieldKindEnumeration:
		sb.WriteString(fmt.Sprintf("\tif val, ok := cf.GetString(%q); ok {\n", field.ID))
		sb.WriteString(fmt.Sprintf("\t\tw.%s = &val\n", field.GoName))
		sb.WriteString("\t}\n\n")

	case polarion.FieldKindInteger:
		sb.WriteString(fmt.Sprintf("\tif val, ok := cf.GetInt(%q); ok {\n", field.ID))
		sb.WriteString(fmt.Sprintf("\t\tw.%s = &val\n", field.GoName))
		sb.WriteString("\t}\n\n")

	case polarion.FieldKindFloat:
		sb.WriteString(fmt.Sprintf("\tif val, ok := cf.GetFloat(%q); ok {\n", field.ID))
		sb.WriteString(fmt.Sprintf("\t\tw.%s = &val\n", field.GoName))
		sb.WriteString("\t}\n\n")

	case polarion.FieldKindBoolean:
		sb.WriteString(fmt.Sprintf("\tif val, ok := cf.GetBool(%q); ok {\n", field.ID))
		sb.WriteString(fmt.Sprintf("\t\tw.%s = &val\n", field.GoName))
		sb.WriteString("\t}\n\n")

	case polarion.FieldKindDate:
		sb.WriteString(fmt.Sprintf("\tif val, ok := cf.GetDateOnly(%q); ok {\n", field.ID))
		sb.WriteString(fmt.Sprintf("\t\tw.%s = &val\n", field.GoName))
		sb.WriteString("\t}\n\n")

	case polarion.FieldKindTime:
		sb.WriteString(fmt.Sprintf("\tif val, ok := cf.GetTimeOnly(%q); ok {\n", field.ID))
		sb.WriteString(fmt.Sprintf("\t\tw.%s = &val\n", field.GoName))
		sb.WriteString("\t}\n\n")

	case polarion.FieldKindDateTime:
		sb.WriteString(fmt.Sprintf("\tif val, ok := cf.GetDateTime(%q); ok {\n", field.ID))
		sb.WriteString(fmt.Sprintf("\t\tw.%s = &val\n", field.GoName))
		sb.WriteString("\t}\n\n")

	case polarion.FieldKindDuration:
		sb.WriteString(fmt.Sprintf("\tif val, ok := cf.GetDuration(%q); ok {\n", field.ID))
		sb.WriteString(fmt.Sprintf("\t\tw.%s = &val\n", field.GoName))
		sb.WriteString("\t}\n\n")

	case polarion.FieldKindText, polarion.FieldKindTextHTML:
		sb.WriteString(fmt.Sprintf("\tif val, ok := cf.GetText(%q); ok {\n", field.ID))
		sb.WriteString(fmt.Sprintf("\t\tw.%s = val\n", field.GoName))
		sb.WriteString("\t}\n\n")

	default:
		// Default to string
		sb.WriteString(fmt.Sprintf("\tif val, ok := cf.GetString(%q); ok {\n", field.ID))
		sb.WriteString(fmt.Sprintf("\t\tw.%s = &val\n", field.GoName))
		sb.WriteString("\t}\n\n")
	}
}

// writeSaveMethod writes the SaveToWorkItem method
func (t *WorkItemTypeTemplate) writeSaveMethod(sb *strings.Builder) {
	sb.WriteString(fmt.Sprintf("// SaveToWorkItem saves the %s fields back to the work item.\n", t.typeName))
	sb.WriteString(fmt.Sprintf("func (w *%s) SaveToWorkItem() {\n", t.typeName))
	sb.WriteString("\tif w.base == nil || w.base.Attributes == nil {\n")
	sb.WriteString("\t\treturn\n")
	sb.WriteString("\t}\n\n")

	if len(t.fields) > 0 {
		sb.WriteString("\tif w.base.Attributes.CustomFields == nil {\n")
		sb.WriteString("\t\tw.base.Attributes.CustomFields = make(map[string]interface{})\n")
		sb.WriteString("\t}\n\n")
		sb.WriteString("\tcf := polarion.CustomFields(w.base.Attributes.CustomFields)\n\n")

		for _, field := range t.fields {
			t.writeSaveField(sb, field)
		}
	}

	sb.WriteString("}\n\n")
}

// writeSaveField writes the code to save a single field
func (t *WorkItemTypeTemplate) writeSaveField(sb *strings.Builder, field FieldInfo) {
	sb.WriteString(fmt.Sprintf("\tif w.%s != nil {\n", field.GoName))

	switch field.Kind {
	case polarion.FieldKindDate:
		sb.WriteString(fmt.Sprintf("\t\tcf.Set(%q, w.%s.String())\n", field.ID, field.GoName))
	case polarion.FieldKindTime:
		sb.WriteString(fmt.Sprintf("\t\tcf.Set(%q, w.%s.String())\n", field.ID, field.GoName))
	case polarion.FieldKindDateTime:
		sb.WriteString(fmt.Sprintf("\t\tcf.Set(%q, w.%s.String())\n", field.ID, field.GoName))
	case polarion.FieldKindDuration:
		sb.WriteString(fmt.Sprintf("\t\tcf.Set(%q, w.%s.String())\n", field.ID, field.GoName))
	case polarion.FieldKindText, polarion.FieldKindTextHTML:
		sb.WriteString(fmt.Sprintf("\t\tcf.Set(%q, w.%s)\n", field.ID, field.GoName))
	default:
		sb.WriteString(fmt.Sprintf("\t\tcf.Set(%q, *w.%s)\n", field.ID, field.GoName))
	}

	sb.WriteString("\t} else {\n")
	sb.WriteString(fmt.Sprintf("\t\tcf.Delete(%q)\n", field.ID))
	sb.WriteString("\t}\n\n")
}

// writeGetterSetter writes getter and setter methods for a field
func (t *WorkItemTypeTemplate) writeGetterSetter(sb *strings.Builder, field FieldInfo) {
	// Getter
	t.writeGetter(sb, field)

	// Setter
	t.writeSetter(sb, field)
}

// writeGetter writes a getter method for a field
func (t *WorkItemTypeTemplate) writeGetter(sb *strings.Builder, field FieldInfo) {
	returnType := strings.TrimPrefix(field.GoType, "*")

	sb.WriteString(fmt.Sprintf("// Get%s returns the %s field value.\n", field.GoName, field.Name))
	if field.Kind == polarion.FieldKindEnumeration && field.EnumName != "" {
		sb.WriteString(fmt.Sprintf("// Enumeration: %s\n", field.EnumName))
	}
	sb.WriteString(fmt.Sprintf("func (w *%s) Get%s() %s {\n", t.typeName, field.GoName, returnType))
	sb.WriteString(fmt.Sprintf("\tif w.%s != nil {\n", field.GoName))
	sb.WriteString(fmt.Sprintf("\t\treturn *w.%s\n", field.GoName))
	sb.WriteString("\t}\n")

	// Return zero value
	switch field.Kind {
	case polarion.FieldKindString, polarion.FieldKindEnumeration:
		sb.WriteString("\treturn \"\"\n")
	case polarion.FieldKindInteger:
		sb.WriteString("\treturn 0\n")
	case polarion.FieldKindFloat:
		sb.WriteString("\treturn 0.0\n")
	case polarion.FieldKindBoolean:
		sb.WriteString("\treturn false\n")
	case polarion.FieldKindDate:
		sb.WriteString("\treturn polarion.DateOnly{}\n")
	case polarion.FieldKindTime:
		sb.WriteString("\treturn polarion.TimeOnly{}\n")
	case polarion.FieldKindDateTime:
		sb.WriteString("\treturn polarion.DateTime{}\n")
	case polarion.FieldKindDuration:
		sb.WriteString("\treturn polarion.Duration{}\n")
	case polarion.FieldKindText, polarion.FieldKindTextHTML:
		sb.WriteString("\treturn polarion.TextContent{}\n")
	default:
		sb.WriteString("\treturn \"\"\n")
	}

	sb.WriteString("}\n\n")
}

// writeSetter writes a setter method for a field
func (t *WorkItemTypeTemplate) writeSetter(sb *strings.Builder, field FieldInfo) {
	paramType := strings.TrimPrefix(field.GoType, "*")

	sb.WriteString(fmt.Sprintf("// Set%s sets the %s field value.\n", field.GoName, field.Name))
	if field.Kind == polarion.FieldKindEnumeration && field.EnumName != "" {
		sb.WriteString(fmt.Sprintf("// Enumeration: %s\n", field.EnumName))
	}
	sb.WriteString(fmt.Sprintf("func (w *%s) Set%s(value %s) {\n", t.typeName, field.GoName, paramType))
	sb.WriteString(fmt.Sprintf("\tw.%s = &value\n", field.GoName))
	sb.WriteString("\tif w.base != nil && w.base.Attributes != nil {\n")
	sb.WriteString("\t\tif w.base.Attributes.CustomFields == nil {\n")
	sb.WriteString("\t\t\tw.base.Attributes.CustomFields = make(map[string]interface{})\n")
	sb.WriteString("\t\t}\n")

	switch field.Kind {
	case polarion.FieldKindDate, polarion.FieldKindTime, polarion.FieldKindDateTime, polarion.FieldKindDuration:
		sb.WriteString(fmt.Sprintf("\t\tw.base.Attributes.CustomFields[%q] = value.String()\n", field.ID))
	default:
		sb.WriteString(fmt.Sprintf("\t\tw.base.Attributes.CustomFields[%q] = value\n", field.ID))
	}

	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")
}

// writeGetBaseMethod writes the GetBase method
func (t *WorkItemTypeTemplate) writeGetBaseMethod(sb *strings.Builder) {
	sb.WriteString(fmt.Sprintf("// GetBase returns the underlying WorkItem for API operations.\n"))
	sb.WriteString(fmt.Sprintf("func (w *%s) GetBase() *polarion.WorkItem {\n", t.typeName))
	sb.WriteString("\treturn w.base\n")
	sb.WriteString("}\n\n")
}

// writeGetIDMethod writes the GetID method
func (t *WorkItemTypeTemplate) writeGetIDMethod(sb *strings.Builder) {
	sb.WriteString(fmt.Sprintf("// GetID returns the work item ID.\n"))
	sb.WriteString(fmt.Sprintf("func (w *%s) GetID() string {\n", t.typeName))
	sb.WriteString("\tif w.base != nil {\n")
	sb.WriteString("\t\treturn w.base.ID\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn \"\"\n")
	sb.WriteString("}\n\n")
}

// writeGetTitleMethod writes the GetTitle method
func (t *WorkItemTypeTemplate) writeGetTitleMethod(sb *strings.Builder) {
	sb.WriteString(fmt.Sprintf("// GetTitle returns the work item title.\n"))
	sb.WriteString(fmt.Sprintf("func (w *%s) GetTitle() string {\n", t.typeName))
	sb.WriteString("\tif w.base != nil && w.base.Attributes != nil {\n")
	sb.WriteString("\t\treturn w.base.Attributes.Title\n")
	sb.WriteString("\t}\n")
	sb.WriteString("\treturn \"\"\n")
	sb.WriteString("}\n")
}
